# Generated by Django 5.2.7 on 2025-10-02 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Care circle name (e.g., 'John's Care Team')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, help_text='Street address line 1', max_length=255)),
                ('address_2', models.CharField(blank=True, help_text='Street address line 2 (apt, suite, etc.)', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
            ],
            options={
                'verbose_name': 'Care Circle',
                'verbose_name_plural': 'Care Circles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('household_role', models.CharField(choices=[('patient', 'Patient'), ('primary_caregiver', 'Primary Caregiver'), ('caregiver', 'Caregiver')], default='caregiver', help_text="User's role: patient (receiving care) or caregiver (providing care)", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('household', models.ForeignKey(blank=True, help_text='The care circle this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='authentication.household')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'firebase_uid'], name='authenticat_email_f3fc66_idx'), models.Index(fields=['household', 'household_role'], name='authenticat_househo_dd1c7d_idx')],
            },
        ),
    ]
