// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHP9TMviIkkdWCkeIcWS2_Mnisu18ykWk',
    appId: '1:47412521285:web:5b84858c31fdfc1708362c',
    messagingSenderId: '47412521285',
    projectId: 'omnyapp-4dc46',
    authDomain: 'omnyapp-4dc46.firebaseapp.com',
    storageBucket: 'omnyapp-4dc46.firebasestorage.app',
    measurementId: 'G-LCV6XSEWM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCfwxXOqwQqGBvAK5DoUaVPCom5yut6c4',
    appId: '1:47412521285:android:0481c59eae8e7de608362c',
    messagingSenderId: '47412521285',
    projectId: 'omnyapp-4dc46',
    storageBucket: 'omnyapp-4dc46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxCYzLtsN1fxHZL3RD-yRvkuO3utJy_PY',
    appId: '1:47412521285:ios:aec509340ea4ceba08362c',
    messagingSenderId: '47412521285',
    projectId: 'omnyapp-4dc46',
    storageBucket: 'omnyapp-4dc46.firebasestorage.app',
    androidClientId: '47412521285-cktj4gi01gl8chk9fpe1f8iiqgit33c2.apps.googleusercontent.com',
    iosClientId: '47412521285-oe6t9il4vurp5hdtsjsmm9dhlfial1ko.apps.googleusercontent.com',
    iosBundleId: 'com.omny.omnyApp',
  );
}
