# Generated by Django 5.2.7 on 2025-10-02 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('watch', 'Smart Watch'), ('sos_button', 'SOS Button')], max_length=50)),
                ('name', models.CharField(help_text='Custom name for the device', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline')], default='active', max_length=20)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery percentage (0-100)', null=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User this device is assigned to (for wearables like watches)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSButtonConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_count', models.IntegerField(choices=[(1, '1 Tap'), (2, '2 Taps'), (3, '3 Taps')], help_text='Number of taps to trigger this action')),
                ('action_type', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS'), ('notification', 'Push Notification'), ('all', 'All (Call + SMS + Notification)')], default='all', help_text='Type of notification to send', max_length=20)),
                ('message_template', models.TextField(help_text='Message template. Use {patient_name}, {location}, {time} as placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='SOS Button device', limit_choices_to={'device_type': 'sos_button'}, on_delete=django.db.models.deletion.CASCADE, related_name='sos_configurations', to='devices.device')),
                ('notify_caregivers', models.ManyToManyField(help_text='Caregivers to notify when this tap pattern is triggered', limit_choices_to={'household_role__in': ['primary_caregiver', 'caregiver']}, related_name='sos_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Button Configuration',
                'verbose_name_plural': 'SOS Button Configurations',
                'ordering': ['device', 'tap_count'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('fall_detected', 'Fall Detected'), ('sos_1_tap', 'SOS - 1 Tap'), ('sos_2_taps', 'SOS - 2 Taps'), ('sos_3_taps', 'SOS - 3 Taps')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], default='high', max_length=20)),
                ('message', models.TextField(help_text='Emergency message/description')),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('partially_sent', 'Partially Sent')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, help_text='Notes from the responder')),
                ('location_data', models.JSONField(blank=True, help_text='GPS coordinates or location data', null=True)),
                ('sensor_data', models.JSONField(blank=True, help_text='Sensor data (e.g., accelerometer readings for falls)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(help_text='Device that triggered the emergency', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='devices.device')),
                ('first_responder', models.ForeignKey(blank=True, help_text='First caregiver to respond', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_responses', to=settings.AUTH_USER_MODEL)),
                ('notified_caregivers', models.ManyToManyField(blank=True, help_text='Caregivers who were notified', related_name='emergency_notifications', to=settings.AUTH_USER_MODEL)),
                ('sos_configuration', models.ForeignKey(blank=True, help_text='SOS configuration used (if this is an SOS event)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='devices.sosbuttonconfiguration')),
            ],
            options={
                'verbose_name': 'Emergency Event',
                'verbose_name_plural': 'Emergency Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Room name (e.g., 'Living Room', 'Master Bathroom')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(help_text='The care circle/household this space belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='authentication.household')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'ordering': ['household', 'name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='space',
            field=models.ForeignKey(blank=True, help_text='Space this device is installed in (for fixed devices like SOS buttons)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.space'),
        ),
        migrations.CreateModel(
            name='DeviceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_battery', 'Low Battery'), ('device_offline', 'Device Offline'), ('maintenance_required', 'Maintenance Required')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('message', models.TextField(help_text='Alert message/description')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional alert data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='Caregiver who acknowledged the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Alert',
                'verbose_name_plural': 'Device Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'alert_type', 'created_at'], name='devices_dev_device__b98800_idx'), models.Index(fields=['is_acknowledged', 'severity'], name='devices_dev_is_ackn_5ba710_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sosbuttonconfiguration',
            index=models.Index(fields=['device', 'tap_count', 'is_active'], name='devices_sos_device__b12756_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosbuttonconfiguration',
            unique_together={('device', 'tap_count')},
        ),
        migrations.AddIndex(
            model_name='emergencyevent',
            index=models.Index(fields=['device', 'event_type', 'created_at'], name='devices_eme_device__7c8fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyevent',
            index=models.Index(fields=['notification_status', 'severity'], name='devices_eme_notific_9b3997_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyevent',
            index=models.Index(fields=['first_responder', 'responded_at'], name='devices_eme_first_r_73b5a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('household', 'name')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id', 'status'], name='devices_dev_device__5f1be1_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type', 'status'], name='devices_dev_device__3e2531_idx'),
        ),
    ]
